### ISSUE TITLE
Same name paper

### ISSUE THREAD

**Issue by SeanLi-OI** [RulinShao/LightSeq#1]
Just a friendly reminder: there are two other papers titled "LightSeq" in ACL'21 and "LightSeq2" in SC'22.
https://arxiv.org/pdf/2010.13887.pdf
https://arxiv.org/pdf/2110.05722.pdf

You've done a great work in accelerating distributed training on sequence level parallelism, perhaps considering a different name would be beneficial.

**Comment by DachengLi1** [comment]
@SeanLi-OI Thanks a lot for the reminder! Yes, we recently also came across these two great papers. We will consider it, thanks!
