### ISSUE TITLE
About Megatron-LM sequence length

### ISSUE THREAD

**Issue by ZhongYingMatrix** [RulinShao/LightSeq#3]
Thx for ur brilliant work!
I have a small question regarding the content of the paper: In Table 1, for the sequence length, will the total length of the Megatron-LM method be equal to the sum of the lengths on each GPU? My understanding is that within the same group of tensor parallelism in Megatron-LM , the input sequence should be the same.
If my understanding is incorrect, please kindly point it out.

**Comment by DachengLi1** [comment]
Yes you are absolutely correct, Megatron-LM uses the global sequence length in the same group of TP! We will update in the paper! Thx for the catch!
