### ISSUE TITLE
how to use your code in other models?

### ISSUE THREAD

**Issue by zxgx** [RulinShao/LightSeq#5]
Hi,

Your code seems pretty neat. I want to try your solution in other transformer models. Can I directly use another model name defined by huggingface as the [ModelArguments](https://github.com/RulinShao/LightSeq/blob/28c3961aa6649eb7df0137f8d70272e50c97a13d/lightseq/train_lightseq_no_trainer.py#L28C7-L28C21)?

**Comment by DachengLi1** [comment]
hi @zxgx thank you very much! The attention part should be generic to other autoregressive models: https://github.com/RulinShao/LightSeq/blob/main/lightseq/lightseq_async_attn.py#L436. You will only need to do a monkey patch to the attention. We didn't test it in other models, but let us know if you encounter any issues!

**Comment by RulinShao** [comment]
> hi @zxgx thank you very much! The attention part should be generic to other autoregressive models: https://github.com/RulinShao/LightSeq/blob/main/lightseq/lightseq_async_attn.py#L436. You will only need to do a monkey patch to the attention. We didn't test it in other models, but let us know if you encounter any issues!

PS: we wrote the lightseq attention api in a similar way as FlashAttention, so one straightforward way is to find where the codes patch FlashAttention and replace FA with LightSeq attention that @DachengLi1 linked to.

**Comment by zxgx** [comment]
Great, thank you for your reply! 😄
