### ISSUE TITLE
Megatron-LM’s communication

### ISSUE THREAD

**Issue by wangpengfei1013** [RulinShao/LightSeq#7]
![image](https://github.com/RulinShao/LightSeq/assets/155146149/cb598382-da78-4ff4-8339-1b49d8e2eed6)

Isn't it four allgather and  reducescatter？

**Comment by DachengLi1** [comment]
<img width="1100" alt="Screenshot 2024-03-18 at 12 32 08 PM" src="https://github.com/RulinShao/LightSeq/assets/28548224/4f6067be-5495-4e88-865a-c6953ff21f2d">
There is an extra all-gather here (*2, two block per layer).

**Comment by wangpengfei1013** [comment]
> <img alt="Screenshot 2024-03-18 at 12 32 08 PM" width="1100" src="https://private-user-images.githubusercontent.com/28548224/313811936-4f6067be-5495-4e88-865a-c6953ff21f2d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MTAyMTgsIm5iZiI6MTcxMDgwOTkxOCwicGF0aCI6Ii8yODU0ODIyNC8zMTM4MTE5MzYtNGY2MDY3YmUtNTQ5NS00ZTg4LTg2NWEtYzY5NTNmZjIxZjJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDAwNTgzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1OTQxMmY5NzA2YjJiMTQ0M2NkMDJhNmIxY2JkNDcyZWQ4Nzc5ZTYwZGVkNzFlZGZjZDk5OGM1MDIwYjVmZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CFgG5hVN5K8Eh3lzKEt83TkjjjYAKwuOa4kocdB8h3I"> There is an extra all-gather here (*2, two block per layer).

Thank you for your answer. I think I understand it
